ctrl_interface_group=0
ap_scan=1
ctrl_interface=/var/run/wpa_supplicant
network={
    proto=WPA2
    pairwise=CCMP
    key_mgmt=WPA-PSK
    priority=2
    ssid="test"
    psk="test12345"
}
network={
    proto=WPA2
    pairwise=CCMP
    key_mgmt=WPA-PSK
    priority=1
    ssid="TEST2"
    psk="39test31"
}
